apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgA+SaJXhjj70xZH+XXKyv/OKI0IEV2K/95bjB6HL3RgTw+Tbxwf7jwsivXVHjbd7c2OKdqjU69NCa9swHIoBeLLJAE0nwtcKoN/hPCc+SPxiuEUuL25vAvXPDYLK85nyAB5ztCJwsgKGnT50TIAuXZ0C8qPnDs2CcCxCF2FzW8ZsGrbzPGGFO5rBOJwzAcXbAUkaJ7ckvfPy3uDDnfQNSWpX1vSENTvgzPFp6fqn2cOa7NqMvoXFJcxViYxp0h1giZJJlArDFNlW2mYa6y2Cu441NzgVNQUf3VjRYUaookg3cETBiwf9usbm39JXx/87Hc4MnuxdNCZxACFSRzSxIjpsSOXcUk6Sm0GFKFyMHmZSiuB0qPtlNKtSNy3iDbQS8QHSD0FDzutafPQz3fWC4ovgso/kdlNcrIxlJfM2X4fAhV7iY9xUfBMYXsYbFsnbdIr3zCc2SdeZJOrMg4xT0K5qCQKnm7H1EzuzIJ1Sp2Z3htR+FA8nMPJ5bXdxgcct7wJFNxKjBWRhkSEYMM3HcaKdkqmzjx8m0n/PR8fSV0IPSEQOSPDdcuOBU3pKEQ2evVaxKXMbBLTMYCuyF7ZK5i96ZkkOIEgbSNcQWzlGEFrJwmqVVFku6e9oB+GqAgZafEeOmqPnu0VU4qYxZgwo8NmI1Y9s358vVqkh1Z8dmilFJ6UAK99QHTPEBPkhxK+d9fWxOkiafdAYsK/succlv3lkSEEgYDgYuLQ/xnrBTQ7sqGxAmdtVTflaxSrSn3u89IuPeQQ6cfN9gp+8i4xQPlOxJOrG4UkN2Xqp39+pWi0FOmNqtPKSs6YLLxPJ6DLWYWZFQ7ztpEetCGReo4irLsWcsg+MFyzInmS9g0NeIL/h5qU/CO4e3xYTuRXENwdXT4gzGOqpb4GfidOSXXqvT3Ph8Np1YBvTjpQf+nCPxjL78U8roXskFRPINIE5L6zE7xpAruM8WIUqIax8S+WfemCOX4Oa3e5kKbYyagiPz3LEYB0R9zh8zWfF4JmRLkBAwP59r1Zv57T4HrWBlJ80COI7fk0B2iaUsMyF6Dnx6miMmZ1XZJ/x/qh10NL5p3FV1NVxj298QxTkMZ/9+JtjmW2y9rjIDjVWJTfmDg0SYUijZABZ7vuzqpk8v7aQod0mGCBnfxOt5yInuuq2s/TbTTR/HyrPeIzEvZyxVohIcIJf5e3V6Kz7RC8VXn5d+xM1lRnBtF/0o6pZROjzr5Srp/S+5lNOneE+nogL0wOzrNkljV1vBnS8x4JqytitsfunBAzPV8Fyna13Pqh166Bbpa6KgkrsWQk90XIX7i83UnRMjQqqeXVx9a40mN691URWoUWoqty99s+WguV2NReORalErSMeu3Zg5xto5EvXUeUvDRnJBcc
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson

