apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ace-config
spec:
  params:
    - name: is-config-repo-url
      type: string
      description: "SSH url of Configuration repository, ex: git@github.com:ace-prod-ref/ace-config.git"

    - name: is-infra-repo-url
      type: string
      description: "SSH url of Infrastructure repository, ex: git@github.com:ace-prod-ref/ace-infra.git"

    - name: git-ops-repo-url
      type: string
      description: "SSH url of GitOps repository, ex: git@github.com:ace-prod-ref/multi-tenancy-gitops-apps.git"

    - name: gitops-apps-repo-full-name
      type: string
      description: "Repo name of GitOps repository, in github.com, ex: ace-prod-ref/multi-tenancy-gitops-apps"

    - name: github-pr-title
      type: string
      default: "Changes by Pipeline run: $(context.pipelineRun.name)"
      description: "Title of pull request"
    - name: github-pr-body
      type: string
      default: "Changes by Pipeline run: $(context.pipelineRun.name)"
      description: "Body of pull request"
    - name: github-pr-token-secret-name
      type: string
      default: cicd-acme
      description: "Personal access token for CICD bot user"

  workspaces:
    - name: shared-workspace
    - name: ace-config-repo-secret
    - name: ace-infra-repo-secret
    - name: gitops-repo-secret

  tasks:
    - name: clone-is-config-repo
      params:
        - name: url
          value: $(params.is-config-repo-url)
        - name: subdirectory
          value: is-config
        - name: deleteExisting
          value: "true"
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: ssh-directory
          workspace: ace-config-repo-secret